name: Nest CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        if: success()

      - name: Build project
        run: |
          npm ci
          npm run build

      - name: Deploy Build to VPS (SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*,package.json,package-lock.json,prisma/*"
          target: "/home/dede/PokemonCenter/back"
          strip_components: 0

      - name: Post-deploy commands (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e   
          
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            nvm use --lts || nvm use 24 || nvm use 18
            
            cd /home/dede/PokemonCenter/back
            
            echo "Nettoyage des anciens modules..."
            rm -rf node_modules
            npm ci --omit=dev
            
            echo "Vérification de la base de données..."
            npx prisma migrate deploy || echo "Pas de migrations à appliquer"
            
                        
            echo "Redémarrage du serveur..."
            hash -r
            $PM2_BIN restart back || $PM2_BIN start dist/main.js --name "back"